[package]
name = "nato_alphabet_rs"
version = "0.1.0"
authors = ["graves501"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
indexmap = "1.7.0"
